include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude: 
    - '**/*_generated.dart'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
