name: test_project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_hooks: ^0.20.0
  logger: ^2.4.0
  get_it: ^8.0.2
  auto_route: ^9.2.1+1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_dotenv: ^5.2.1
  retrofit: ^4.4.1
  permission_handler: ^11.0.1
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  top_snackbar_flutter: ^3.1.0
  flutter_svg: ^2.0.9
  file_picker: ^8.1.4
  image_picker: ^1.1.0
  equatable: ^2.0.5
  sqflite: ^2.4.1

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0 
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  retrofit_generator: ^9.1.7
  freezed: ^2.5.2
  json_serializable: ^6.4.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/images/
    - assets/icons/
    - assets/svgs/

flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    exclude:
      - .env.*
      - .gitkeep
      - config/
    outputs:
      class_name: AppAssets
