name: Trigger Staging Build

on:
  workflow_dispatch:

jobs:
  trigger_staging:
    uses: ./.github/workflows/web_build.yaml
    with:
      init_env: "staging"
    secrets:
      base_url: ${{ secrets.STAGING_BASE_URL }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
